---
name: ansible test

on:
  push:
    branches:
      - master

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout codebase
        uses: actions/checkout@v4

      - name: Setup SSH
        shell: bash
        run: |
          eval $(ssh-agent -s)
          install -m 600 -D /dev/null ~/.ssh/id_ed25519
          echo "${{secrets.SSH_KEY}}" > ~/.ssh/id_ed25519
          ssh-keyscan -t rsa,dsa,ecdsa,ed25519 ${{secrets.SSH_HOST}} >> ~/.ssh/known_hosts

      - name: Run playbook
        shell: bash
        run: |
          service ssh status
          ansible-playbook --private-key ~/.ssh/id_ed25519 -i ${{secrets.SSH_HOST}}, main.yml
